####################################################################################################
# Makefile generated by updateMakefile.py
# Version 1.6 
# Last run: 2019-03-26 21:00:34.779114 
####################################################################################################

######################################
# target
######################################
TARGET = dash_stm32f7_sw


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
lvgl/lv_core/lv_group.c \
lvgl/lv_core/lv_indev.c \
lvgl/lv_core/lv_lang.c \
lvgl/lv_core/lv_obj.c \
lvgl/lv_core/lv_refr.c \
lvgl/lv_core/lv_style.c \
lvgl/lv_core/lv_vdb.c \
lvgl/lv_draw/lv_draw_arc.c \
lvgl/lv_draw/lv_draw.c \
lvgl/lv_draw/lv_draw_img.c \
lvgl/lv_draw/lv_draw_label.c \
lvgl/lv_draw/lv_draw_line.c \
lvgl/lv_draw/lv_draw_rbasic.c \
lvgl/lv_draw/lv_draw_rect.c \
lvgl/lv_draw/lv_draw_triangle.c \
lvgl/lv_draw/lv_draw_vbasic.c \
lvgl/lv_fonts/lv_font_builtin.c \
lvgl/lv_fonts/lv_font_dejavu_10.c \
lvgl/lv_fonts/lv_font_dejavu_10_cyrillic.c \
lvgl/lv_fonts/lv_font_dejavu_10_latin_sup.c \
lvgl/lv_fonts/lv_font_dejavu_20.c \
lvgl/lv_fonts/lv_font_dejavu_20_cyrillic.c \
lvgl/lv_fonts/lv_font_dejavu_20_latin_sup.c \
lvgl/lv_fonts/lv_font_dejavu_30.c \
lvgl/lv_fonts/lv_font_dejavu_30_cyrillic.c \
lvgl/lv_fonts/lv_font_dejavu_30_latin_sup.c \
lvgl/lv_fonts/lv_font_dejavu_40.c \
lvgl/lv_fonts/lv_font_dejavu_40_cyrillic.c \
lvgl/lv_fonts/lv_font_dejavu_40_latin_sup.c \
lvgl/lv_fonts/lv_font_monospace_8.c \
lvgl/lv_fonts/lv_font_symbol_10.c \
lvgl/lv_fonts/lv_font_symbol_20.c \
lvgl/lv_fonts/lv_font_symbol_30.c \
lvgl/lv_fonts/lv_font_symbol_40.c \
lvgl/lv_hal/lv_hal_disp.c \
lvgl/lv_hal/lv_hal_indev.c \
lvgl/lv_hal/lv_hal_tick.c \
lvgl/lv_misc/lv_anim.c \
lvgl/lv_misc/lv_area.c \
lvgl/lv_misc/lv_circ.c \
lvgl/lv_misc/lv_color.c \
lvgl/lv_misc/lv_font.c \
lvgl/lv_misc/lv_fs.c \
lvgl/lv_misc/lv_gc.c \
lvgl/lv_misc/lv_ll.c \
lvgl/lv_misc/lv_log.c \
lvgl/lv_misc/lv_math.c \
lvgl/lv_misc/lv_mem.c \
lvgl/lv_misc/lv_task.c \
lvgl/lv_misc/lv_templ.c \
lvgl/lv_misc/lv_txt.c \
lvgl/lv_misc/lv_ufs.c \
lvgl/lv_objx/lv_arc.c \
lvgl/lv_objx/lv_bar.c \
lvgl/lv_objx/lv_btn.c \
lvgl/lv_objx/lv_btnm.c \
lvgl/lv_objx/lv_calendar.c \
lvgl/lv_objx/lv_canvas.c \
lvgl/lv_objx/lv_cb.c \
lvgl/lv_objx/lv_chart.c \
lvgl/lv_objx/lv_cont.c \
lvgl/lv_objx/lv_ddlist.c \
lvgl/lv_objx/lv_gauge.c \
lvgl/lv_objx/lv_imgbtn.c \
lvgl/lv_objx/lv_img.c \
lvgl/lv_objx/lv_kb.c \
lvgl/lv_objx/lv_label.c \
lvgl/lv_objx/lv_led.c \
lvgl/lv_objx/lv_line.c \
lvgl/lv_objx/lv_list.c \
lvgl/lv_objx/lv_lmeter.c \
lvgl/lv_objx/lv_mbox.c \
lvgl/lv_objx/lv_objx_templ.c \
lvgl/lv_objx/lv_page.c \
lvgl/lv_objx/lv_preload.c \
lvgl/lv_objx/lv_roller.c \
lvgl/lv_objx/lv_slider.c \
lvgl/lv_objx/lv_spinbox.c \
lvgl/lv_objx/lv_sw.c \
lvgl/lv_objx/lv_table.c \
lvgl/lv_objx/lv_tabview.c \
lvgl/lv_objx/lv_ta.c \
lvgl/lv_objx/lv_tileview.c \
lvgl/lv_objx/lv_win.c \
lvgl/lv_porting/lv_port_disp_templ.c \
lvgl/lv_porting/lv_port_fs_templ.c \
lvgl/lv_porting/lv_port_indev_templ.c \
lvgl/lv_themes/lv_theme_alien.c \
lvgl/lv_themes/lv_theme.c \
lvgl/lv_themes/lv_theme_default.c \
lvgl/lv_themes/lv_theme_material.c \
lvgl/lv_themes/lv_theme_mono.c \
lvgl/lv_themes/lv_theme_nemo.c \
lvgl/lv_themes/lv_theme_night.c \
lvgl/lv_themes/lv_theme_templ.c \
lvgl/lv_themes/lv_theme_zen.c \
lv_drivers/display/fbdev.c \
lv_drivers/display/monitor.c \
lv_drivers/display/R61581.c \
lv_drivers/display/SSD1963.c \
lv_drivers/display/ST7565.c \
lv_drivers/indev/AD_touch.c \
lv_drivers/indev/evdev.c \
lv_drivers/indev/FT5406EE8.c \
lv_drivers/indev/keyboard.c \
lv_drivers/indev/mouse.c \
lv_drivers/indev/mousewheel.c \
lv_drivers/indev/XPT2046.c \
Src/main.c \
Src/stm32f7xx_it.c \
Src/stm32f7xx_hal_msp.c \
Src/stm32f7xx_hal_timebase_tim.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_can.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc_ex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_exti.c \
Src/system_stm32f7xx.c

# ASM sources
ASM_SOURCES =  \
startup_stm32f746xx.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m7

# fpu
FPU = -mfpu=fpv5-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F746xx


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-IInc \
-IDrivers/STM32F7xx_HAL_Driver/Inc \
-IDrivers/STM32F7xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32F7xx/Include \
-IDrivers/CMSIS/Include
-IDrivers/CMSIS/Include


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F746NGHx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***

#######################################
# Print makefile variables
#######################################
print-%:
	@echo VARIABLE=$($*)
